language: node_js
node_js:
  - "8.9.4"

branches:
  only:
    - master

script:
  - npm run deploy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: .
  on:
    branch: master
